### ISSUE TITLE
what if I login using google mail instead of username and password?

### ISSUE THREAD

**Issue by gospel99** [Amsal1/Moodle-Attendance-Script#1]
what if I login using google mail instead of username and password?

**Comment by Amsal1** [comment]
You mean you enter email of @gmail.com in place of username on Moodle login portal?

Or you mean they ask you guys to login with Google Account? Send me a screenshot of your Moodle Login page.

If you just need to enter email instead of a username or some number in the Login page, you can still use this script just like this and enter your email instead of username

**Comment by gospel99** [comment]
![edu](https://user-images.githubusercontent.com/31013266/134279454-70991018-9dcf-44dd-8b60-1f6b08f7d9a0.png)
like this

**Comment by Amsal1** [comment]
Ah, that is not supported! You can use the username/password to login though
